{
 "title": "OCI APIGateway",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "region", "query": "regions($tenancy)" },
   { "name": "compartment", "query": "compartments($tenancy)" },
   {
    "name": "namespace",
    "query": "namespaces($region,$compartment)"
   },
   {
    "name": "resourcegroup",
    "query": "resourcegroups($region, $compartment, $namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "2XX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "groupBy": "select option (optional)",
     "intervalLabel": "1 minute",
     "metric": "select metric",
     "metricNames": "$resourcegroup",
     "namespace": "$namespace",
     "queryText": "HttpRequests[1m]{deploymentName = \"users-api\", route =~ \"/*\",httpStatusCategory = \"2XX\"}.groupBy(route,deploymentName).count()",
     "queryTextRaw": "HttpRequests[1m]{deploymentName = \"users-api\", route =~ \"/*\",httpStatusCategory = \"2XX\"}.groupBy(route,deploymentName).count()",
     "region": "$region",
     "resourcegroup": "$resourcegroup",
     "statistic": "count()",
     "statisticLabel": "count",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "3XX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "groupBy": "select option (optional)",
     "intervalLabel": "1 minute",
     "metric": "select metric",
     "metricNames": "$resourcegroup",
     "namespace": "$namespace",
     "queryText": "HttpRequests[1m]{deploymentName = \"users-api\", route =~ \"/*\",httpStatusCategory = \"3XX\"}.groupBy(route,deploymentName).count()",
     "queryTextRaw": "HttpRequests[1m]{deploymentName = \"users-api\", route =~ \"/*\",httpStatusCategory = \"3XX\"}.groupBy(route,deploymentName).count()",
     "region": "$region",
     "resourcegroup": "$resourcegroup",
     "statistic": "count()",
     "statisticLabel": "count",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "4XX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "groupBy": "select option (optional)",
     "intervalLabel": "1 minute",
     "metric": "select metric",
     "metricNames": "$resourcegroup",
     "namespace": "$namespace",
     "queryText": "HttpRequests[1m]{deploymentName = \"users-api\", route =~ \"/*\",httpStatusCategory = \"4XX\"}.groupBy(route,deploymentName).count()",
     "queryTextRaw": "HttpRequests[1m]{deploymentName = \"users-api\", route =~ \"/*\",httpStatusCategory = \"4XX\"}.groupBy(route,deploymentName).count()",
     "region": "$region",
     "resourcegroup": "$resourcegroup",
     "statistic": "count()",
     "statisticLabel": "count",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "5XX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "groupBy": "select option (optional)",
     "intervalLabel": "1 minute",
     "metric": "select metric",
     "metricNames": "$resourcegroup",
     "namespace": "$namespace",
     "queryText": "HttpRequests[1m]{deploymentName = \"users-api\", route =~ \"/*\",httpStatusCategory = \"5XX\"}.groupBy(route,deploymentName).count()",
     "queryTextRaw": "HttpRequests[1m]{deploymentName = \"users-api\", route =~ \"/*\",httpStatusCategory = \"5XX\"}.groupBy(route,deploymentName).count()",
     "region": "$region",
     "resourcegroup": "$resourcegroup",
     "statistic": "count()",
     "statisticLabel": "count",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  },
  {
   "title": "HttpRequestCount",
   "type": "timeseries",
   "description": "http request count average per min",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "compartment": "$compartment",
     "compartmentName": "$compartment",
     "groupBy": "select option (optional)",
     "intervalLabel": "1 minute",
     "metric": "select metric",
     "metricNames": "$namespace",
     "namespace": "$namespace",
     "queryText": "HttpRequests[1m]{resourceName = \"api-gw-demo\", deploymentName =~ \"*\"}.groupBy(deploymentName).count()",
     "queryTextRaw": "HttpRequests[1m]{resourceName = \"api-gw-demo\", deploymentName =~ \"*\"}.groupBy(deploymentName).count()",
     "region": "$region",
     "statistic": "count()",
     "statisticLabel": "count",
     "tenancy": "DEFAULT/",
     "tenancyName": "DEFAULT/"
    }
   ]
  }
 ]
}